const actionTypes={
    loginActions:{
        LOGIN_START:"LOGIN_START",
        LOGIN_SUCCESS:"LOGIN_SUCCESS",
        LOGIN_FAIL:"LOGIN_FAIL",
        LOGOUT:"LOGOUT"
    },
    userActions:{
        FETCH_USER_START:"FETCH_USER_START",
        FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
        FETCH_USER_FAIL:"FETCH_USER_FAIL",
        UPDATE_USER_START:"UPDATE_USER_START",
        UPDATE_USER_SUCCESS:"UPDATE_USER_SUCCESS",
        UPDATE_USER_FAIL:"UPDATE_USER_FAIL"
    }
}

export default actionTypes